import type { Lang } from './content';

/** Interface copy that isn't part of the portfolio content itself. */
export const UI = {
  en: {
    nav: { about: 'About', experience: 'Experience', projects: 'Projects', skills: 'Skills', contact: 'Contact' },
    skipToContent: 'Skip to content',
    resume: 'Resume',
    downloadResume: 'Download resume',
    getInTouch: 'Get in touch',
    switchLang: 'Voir en français',
    langShort: 'FR',
    toggleTheme: 'Toggle dark mode',
    menu: 'Menu',
    close: 'Close',
    photoAlt: 'Portrait of Abdoul Aziz Maazou',
    sections: {
      about: 'About',
      experience: 'Experience',
      education: 'Education',
      projects: 'Projects',
      skills: 'Skills',
      interests: 'Beyond the code',
      contact: 'Contact',
    },
    aboutTitle: 'Engineer by training, builder by habit.',
    experienceTitle: 'Where I’ve worked.',
    educationTitle: 'Where I studied.',
    projectsTitle: 'Things I’ve built.',
    projectsIntro: 'Professional tools, research prototypes and a couple of games. Open a project for the details.',
    skillsTitle: 'My toolbox.',
    interestsTitle: 'When the laptop closes.',
    contactTitle: 'Let’s build something together.',
    contactIntro: 'Whether it’s a role, a collaboration or just a chat about AI, Angular or game jams — my inbox is open.',
    spokenLanguages: 'Languages',
    present: 'Present',
    filters: { all: 'All', web: 'Web', ai: 'AI & vision', games: 'Games' },
    viewProject: 'View details',
    play: 'Play on itch.io',
    source: 'Source code',
    visit: 'Visit site',
    copyEmail: 'Copy email',
    copied: 'Copied!',
    builtWith: 'Designed & built with Angular.',
    viewSource: 'Source on GitHub',
    backToTop: 'Back to top',
  },
  fr: {
    nav: { about: 'Profil', experience: 'Expérience', projects: 'Projets', skills: 'Compétences', contact: 'Contact' },
    skipToContent: 'Aller au contenu',
    resume: 'CV',
    downloadResume: 'Télécharger mon CV',
    getInTouch: 'Me contacter',
    switchLang: 'View in English',
    langShort: 'EN',
    toggleTheme: 'Basculer le mode sombre',
    menu: 'Menu',
    close: 'Fermer',
    photoAlt: 'Portrait d’Abdoul Aziz Maazou',
    sections: {
      about: 'Profil',
      experience: 'Expérience',
      education: 'Formation',
      projects: 'Projets',
      skills: 'Compétences',
      interests: 'Hors du code',
      contact: 'Contact',
    },
    aboutTitle: 'Ingénieur de formation, bâtisseur par habitude.',
    experienceTitle: 'Mon parcours professionnel.',
    educationTitle: 'Ma formation.',
    projectsTitle: 'Ce que j’ai construit.',
    projectsIntro: 'Des outils professionnels, des prototypes de recherche et quelques jeux. Ouvrez un projet pour en savoir plus.',
    skillsTitle: 'Ma boîte à outils.',
    interestsTitle: 'Quand l’ordinateur se ferme.',
    contactTitle: 'Construisons quelque chose ensemble.',
    contactIntro: 'Un poste, une collaboration ou simplement une discussion sur l’IA, Angular ou les game jams — ma boîte mail est ouverte.',
    spokenLanguages: 'Langues',
    present: 'Aujourd’hui',
    filters: { all: 'Tous', web: 'Web', ai: 'IA & vision', games: 'Jeux' },
    viewProject: 'Voir le détail',
    play: 'Jouer sur itch.io',
    source: 'Code source',
    visit: 'Voir le site',
    copyEmail: 'Copier l’e-mail',
    copied: 'Copié !',
    builtWith: 'Conçu et développé avec Angular.',
    viewSource: 'Code sur GitHub',
    backToTop: 'Retour en haut',
  },
} satisfies Record<Lang, unknown>;

export type UiStrings = (typeof UI)['en'];
