import type { Lang } from './content';

/** Interface copy that isn't part of the portfolio content itself. */
export const UI = {
  en: {
    nav: { about: 'about', journey: 'journey', projects: 'projects', stack: 'stack', contact: 'contact' },
    skipToContent: 'Skip to content',
    cv: 'cv.pdf',
    downloadCv: 'Download CV',
    contactMe: 'Contact me',
    switchLang: 'Voir en français',
    langShort: 'FR',
    toggleTheme: 'Toggle dark mode',
    menu: 'Menu',
    close: 'Close',
    photoAlt: 'Portrait of Abdoul Aziz Maazou',
    hero: {
      status: 'online',
      frame: 'frame',
      detections: 'detections',
      runningOn: 'running on',
    },
    files: {
      about: 'about.md',
      journey: 'git log --graph',
      projects: 'projects/',
      stack: 'stack.json',
      interests: 'hobbies/',
      contact: 'contact.sh',
    },
    titles: {
      about: 'Seeing, reasoning, shipping.',
      journey: 'From Niamey to Grenoble.',
      projects: 'Things I’ve built.',
      stack: 'The toolbox.',
      interests: 'Also detected, off the clock.',
      contact: 'Let’s build AI that helps.',
    },
    journeyIntro: 'Every stop, as a commit. Education branched into industry in 2023.',
    projectsIntro: 'AI products, research prototypes and a couple of games. Open one to read its README.',
    stackIntro: 'Pulled from what I actually use at work and in my projects.',
    contactIntro: 'A role, a collaboration or a chat about agents, vision or game jams — my inbox is open.',
    yaml: {
      fluent: 'fluent',
      professional: 'professional',
      native: 'native',
      assessment: 'LinkedIn skill assessment',
      degree: 'M.Eng. images, signals & data science',
    },
    present: 'present',
    head: 'HEAD → main',
    edu: 'edu',
    filters: { all: 'all', ai: 'ai', games: 'games', web: 'web' },
    viewProject: 'Read the README',
    play: 'Play on itch.io',
    source: 'Source',
    visit: 'Visit',
    copy: 'copy',
    copied: 'copied ✓',
    builtWith: 'Designed & built with Angular — prerendered, bilingual, zoneless.',
    viewSource: 'source',
    backToTop: 'Back to top',
    logoLab: 'Logo lab',
    logoLabHint: 'Pick a mark — it updates the whole page and the favicon.',
  },
  fr: {
    nav: { about: 'profil', journey: 'parcours', projects: 'projets', stack: 'stack', contact: 'contact' },
    skipToContent: 'Aller au contenu',
    cv: 'cv.pdf',
    downloadCv: 'Télécharger le CV',
    contactMe: 'Me contacter',
    switchLang: 'View in English',
    langShort: 'EN',
    toggleTheme: 'Basculer le mode sombre',
    menu: 'Menu',
    close: 'Fermer',
    photoAlt: 'Portrait d’Abdoul Aziz Maazou',
    hero: {
      status: 'en ligne',
      frame: 'image',
      detections: 'détections',
      runningOn: 'tourne sur',
    },
    files: {
      about: 'profil.md',
      journey: 'git log --graph',
      projects: 'projets/',
      stack: 'stack.json',
      interests: 'loisirs/',
      contact: 'contact.sh',
    },
    titles: {
      about: 'Voir, raisonner, livrer.',
      journey: 'De Niamey à Grenoble.',
      projects: 'Ce que j’ai construit.',
      stack: 'La boîte à outils.',
      interests: 'Aussi détecté, hors du bureau.',
      contact: 'Construisons une IA utile.',
    },
    journeyIntro: 'Chaque étape, comme un commit. La formation a bifurqué vers l’industrie en 2023.',
    projectsIntro: 'Des produits d’IA, des prototypes de recherche et quelques jeux. Ouvrez-en un pour lire son README.',
    stackIntro: 'Ce que j’utilise réellement, au travail et dans mes projets.',
    contactIntro: 'Un poste, une collaboration ou une discussion sur les agents, la vision ou les game jams — ma boîte mail est ouverte.',
    yaml: {
      fluent: 'courant',
      professional: 'professionnel',
      native: 'maternelle',
      assessment: 'évaluation LinkedIn',
      degree: 'ingénieur images, signaux & données',
    },
    present: 'aujourd’hui',
    head: 'HEAD → main',
    edu: 'formation',
    filters: { all: 'tous', ai: 'ia', games: 'jeux', web: 'web' },
    viewProject: 'Lire le README',
    play: 'Jouer sur itch.io',
    source: 'Code',
    visit: 'Voir',
    copy: 'copier',
    copied: 'copié ✓',
    builtWith: 'Conçu et développé avec Angular — pré-rendu, bilingue, sans zone.js.',
    viewSource: 'code source',
    backToTop: 'Retour en haut',
    logoLab: 'Labo logo',
    logoLabHint: 'Choisissez un logo — il met à jour toute la page et le favicon.',
  },
} satisfies Record<Lang, unknown>;

export type UiStrings = (typeof UI)['en'];
