import type { Lang } from './content';

/** Interface copy that isn't part of the portfolio content itself. */
export const UI = {
  en: {
    nav: { experience: 'Experience', work: 'Work', about: 'About', contact: 'Contact' },
    skipToContent: 'Skip to content',
    resume: 'Résumé',
    resumePdf: 'Résumé PDF',
    downloadResume: 'Download résumé',
    email: 'Email me',
    switchLang: 'Voir en français',
    langShort: 'FR',
    photoAlt: 'Portrait of Abdoul Aziz Maazou',
    facts: { now: 'Now', contract: 'Contract', based: 'Based in', speaks: 'Speaks' },
    sections: {
      experience: 'Experience',
      work: 'Work',
      about: 'About',
      skills: 'Skills',
      games: 'Games',
      education: 'Education',
    },
    intro: {
      experience: 'From a steel line to a **permanent AI engineer** role. Four roles, two companies, since 2023.',
      work: 'Three AI systems built in industry, from the first prototype to the people who use them.',
      about: 'From Niamey to Grenoble, by way of Rabat and Strasbourg.',
      skills: 'What I work with every day, and where I learned it.',
      games: 'Unity games with soundtracks I compose in FL Studio. Both are being upgraded; new clips and tracks soon.',
    },
    now: 'now',
    award: 'Award',
    present: 'now',
    stack: 'Stack',
    showRole: 'Show details',
    caseStudy: 'Case study',
    problem: 'Problem',
    builtWith: 'Built with',
    watchDemo: 'Watch the public demo',
    route: 'Route',
    outside: 'Outside work',
    skillGroups: 'Skills',
    clipSoon: 'Gameplay clip soon',
    upgrading: 'Upgrade in progress',
    play: 'Play in the browser',
    soundtrack: 'Original soundtracks, composed in FL Studio',
    soundtrackSoon: 'New versions soon',
    txbot: {
      label: 'Illustration of TxBot: a question, retrieval over documents and TEEXMA data, and an answer that cites its sources',
      q: 'Which grades reach a proof stress above 900 MPa?',
      a: 'I found matching grades in the materials database. Here they are, with the records I used.',
      s1: 'TEEXMA · tensile tests',
      s2: 'Internal datasheet',
      flow: ['Question', 'Retrieval · LangChain', 'Docs + TEEXMA', 'Grounded answer'],
      cap: 'Illustration · the real tool is internal',
    },
    contactAsk: 'Hiring for AI, LLM or computer-vision work? Write to me. I answer in French, English or Hausa.',
    yr: (n: number) => `${n} yr${n > 1 ? 's' : ''}`,
    mo: (n: number) => `${n} mo`,
    footer: 'Grenoble, France',
  },
  fr: {
    nav: { experience: 'Expérience', work: 'Projets', about: 'À propos', contact: 'Contact' },
    skipToContent: 'Aller au contenu',
    resume: 'CV',
    resumePdf: 'CV PDF',
    downloadResume: 'Télécharger le CV',
    email: 'M’écrire',
    switchLang: 'View in English',
    langShort: 'EN',
    photoAlt: 'Portrait d’Abdoul Aziz Maazou',
    facts: { now: 'Poste', contract: 'Contrat', based: 'Basé à', speaks: 'Langues' },
    sections: {
      experience: 'Expérience',
      work: 'Projets',
      about: 'À propos',
      skills: 'Compétences',
      games: 'Jeux',
      education: 'Formation',
    },
    intro: {
      experience: 'D’une ligne d’acier à un poste d’**ingénieur IA en CDI**. Quatre postes, deux entreprises, depuis 2023.',
      work: 'Trois systèmes d’IA réalisés en entreprise, du premier prototype jusqu’aux utilisateurs.',
      about: 'De Niamey à Grenoble, en passant par Rabat et Strasbourg.',
      skills: 'Ce que j’utilise au quotidien, et où je l’ai appris.',
      games: 'Des jeux Unity dont je compose la bande-son sur FL Studio. Les deux sont en cours de mise à jour ; nouvelles vidéos et morceaux bientôt.',
    },
    now: 'auj.',
    award: 'Distinction',
    present: 'aujourd’hui',
    stack: 'Outils',
    showRole: 'Voir le détail',
    caseStudy: 'Étude de cas',
    problem: 'Problème',
    builtWith: 'Réalisé avec',
    watchDemo: 'Voir la démo publique',
    route: 'Parcours',
    outside: 'En dehors du travail',
    skillGroups: 'Compétences',
    clipSoon: 'Vidéo de gameplay bientôt',
    upgrading: 'Mise à jour en cours',
    play: 'Jouer dans le navigateur',
    soundtrack: 'Bandes-son originales, composées sur FL Studio',
    soundtrackSoon: 'Nouvelles versions bientôt',
    txbot: {
      label: 'Illustration de TxBot : une question, une recherche dans les documents et les données TEEXMA, puis une réponse qui cite ses sources',
      q: 'Quelles nuances dépassent 900 MPa de limite d’élasticité ?',
      a: 'J’ai trouvé des nuances correspondantes dans la base matériaux. Les voici, avec les fiches utilisées.',
      s1: 'TEEXMA · essais de traction',
      s2: 'Fiche technique interne',
      flow: ['Question', 'Recherche · LangChain', 'Docs + TEEXMA', 'Réponse sourcée'],
      cap: 'Illustration · l’outil réel est interne',
    },
    contactAsk: 'Vous recrutez pour de l’IA, des LLM ou de la vision par ordinateur ? Écrivez-moi. Je réponds en français, en anglais ou en haoussa.',
    yr: (n: number) => `${n} an${n > 1 ? 's' : ''}`,
    mo: (n: number) => `${n} mois`,
    footer: 'Grenoble, France',
  },
} satisfies Record<Lang, unknown>;

export type UiStrings = (typeof UI)['en'];
